### ISSUE TITLE
Thousands of leaked objects from Dynamic Library?

### ISSUE THREAD

**Issue by germolinal** [adah1972/nvwa#2]
Hello, 

I am using debug_new.h for verifying memory leaks in a program of mine; and there were 2317 reported! with the message that was something like:

```
Leaked object at 0x7facced07e20 (size 48, 0x104c62c31)
```
After all those, a message said
```
*** 2317 leaks found
```

and then, I get 1642 messages saying
```
delete: freed 0x7facced38e00 (size 112, 115248 bytes still allocated)
```

So, I started looking for the source of leakage, and it seems to come from a Dynamic Library I am using. Since it is a closed API, I cannot really debug it. Is this normal behavior? 

Any advice? I am not an advanced programmer, an I am not even sure what is going on.

Thanks!

**Comment by adah1972** [comment]
Many things can cause memory leaks, and here are a few hints for debugging memory issues:

- It could be intentional to let the operating system free allocated memory on program exit (though I would not advocate such practices). It is OK if such leaks are more or less fixed-size.
- In the Windows world, things are much more complicated when multiple DLLs/runtimes are involved. Specifically, if the main program is linked with debug_new.obj, a DLL is not linked with debug_new.obj, both the main program and the DLL is linked with the same DLL runtime (/MD, msvcrt.lib), and memory is allocated from the main program but deallocated from the DLL, *then* debug_new cannot intercept the deallocation routines and will report false positives. My general practice is always allocate and deallocate from the same place and avoid such scenarios.
- Real memory leaks happened. If the reported leaks are bigger when more data is processed or when the program runs longer, you probably need to worry.

**Comment by germolinal** [comment]
Hello again, and thanks for your answer and your tools... very useful!

I am working on macOS; and unfortunately I cannot fix it myself (I will report it). Is there any way of ignoring some sections of the code (i.e. the one I cannot fix)?

Best,

**Comment by adah1972** [comment]
I think you can leverage the source code report capabilities (you need to include nvwa/debug_new.h) and ignore reports that do not have a source line number...

**Comment by germolinal** [comment]
Excellent! Will do.... thanks very much !
